spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://127.0.0.1:3306/fan?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    username: root
#    password: 8690236
#  profiles:
#    active: dev



#redis配置
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 0
#    timeout: 2000
#    lettuce:
#      pool:
#        min-idle: 0
#        max-idle: 8
#        max-active: 8
#        max-wait: -1ms
#    password: 8690236

